### ISSUE TITLE
`type` field in the twitchemotes resolver is empty and unnecessary

### ISSUE THREAD

**Issue by zneix** [Chatterino/api#102]
In twitchemtoes resolver, field `type` is not / no longer returned in [twitchemotes' API](https://twitchemotes.com/apidocs), as far as I investigated in chatterino's source code, that field is present in the `Emote` struct, but not utilized in any way. I suggest we simply remove it.
Example response: https://braize.pajlada.com/chatterino/twitchemotes/set/302023435/

**Comment by pajlada** [comment]
the `type` field is required for parsing in Chatterino (at least before https://github.com/Chatterino/chatterino2/pull/2539 is merged) so we will not be modifying any fields, even if it's unused
