### ISSUE TITLE
Twitch Profile support

### ISSUE THREAD

**Issue by pajlada** [Chatterino/api#132]
**What service do you want support added for?**

Add support for twitch.tv profile links

**Links**

1.  https://twitch.tv/pajlada
2.  https://www.twitch.tv/forsen
3.  https://www.twitch.tv/fourtf

**Thumbnail**

Profile image
Live status?
Bio?
Followers?

**Additional information**

https://dev.twitch.tv/

**Comment by pajlada** [comment]
I've marked this as a good first issue - if you want to start working on this please let me know and I will assign you to this issue so we don't get duplicate work done.

**Comment by leon-richardt** [comment]
Also make sure link such as 

- https://twitch.tv/following
-  https://www.twitch.tv/directory
-  https://www.twitch.tv/inventory
- etc.

are handled correctly

**Comment by jammehcow** [comment]
Happy to pick up after #157 is closed

**Comment by zneix** [comment]
> Happy to pick up after #157 is closed

glhf 😉

**Comment by jammehcow** [comment]
`helix` package doesn't have the `created_at` field exported for users. Created a PR to add it.

**Comment by pajlada** [comment]
This one is open for grabs if anyone wants to check this out, happy to help guide anyone looking to make their first contribution

**Comment by silaselisha** [comment]
@pajlada I would like to make my first contribution. I'll appreciate your guidance guidance.

**Comment by pajlada** [comment]
This should be part of the `internal/resolvers/twitch` package
You have to extend the TwitchAPIClient defined in its `initialize.go` file to support [this function](https://pkg.go.dev/github.com/nicklaw5/helix/v2#Client.GetUsers)
You need to define an additional resolver (see its Clip Resolver) that matches Twitch profile URLs, that then call the above-mentioned function to get information about the user
I'm not sure exactly what information would be nice to show, or in what format. I'd be happy to let you experiment with that and see what you think works best, and then we can iterate on that together.

Let me know if that helps or if there's any further guidance that would be useful @silaselisha

**Comment by silaselisha** [comment]
@pajlada I'll experiment with this, for any query I'll let you know.

**Comment by M4tthewDE** [comment]
I would like to build a resolver for twitch users, feel free to assign the issue to me.
