### ISSUE TITLE
Migrate Twitch clips resolver to Helix API

### ISSUE THREAD

**Issue by zneix** [Chatterino/api#143]
Twitch has recently added `duration` field to Helix's Get Clips endpoint. We could migrate from gotwitch to [helix](https://github.com/nicklaw5/helix) library, which already has added support for duration field in Get Clips method.

I'll go ahead, update branch on my fork (which I've been already maintaining for quite a while) unless someone finds a better Helix library.

**Comment by pajlada** [comment]
Closed by #144
