### ISSUE TITLE
Split Build CI action into separate build and test actions

### ISSUE THREAD

**Issue by zneix** [Chatterino/api#145]
Currently, both building and testing is being handled within `Build` action on the CI. I believe this should be split into 2 separate sets of actions to make it more obvious what's going on when, for example, build succeeds, but tests fail. That'd just make things a bit more clean.

**Comment by pajlada** [comment]
After further consideration, I don't think the overhead added for this feature is worth it. Adding a separate step for this would mean the following steps are repeated 6 times (build matrix, 2 go versions * 3 operating systems): setup go environment, download project dependencies, build project
