### ISSUE TITLE
Facebook oEmbed Changes

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/api#161]
Refer this article: https://developers.facebook.com/docs/plugins/oembed/

The oEmbed product has been replaced with the oEmbed Read feature. If you implemented the oEmbed product before June 8, 2021, you have until September 7, 2021 to complete App Review for the oEmbed Read feature. If you have not been approved for the oEmbed Read feature by September 7, 2021, your oEmbed implementations will fail to load.

I don't really help with the api that often and am unsure if this actually affects us, but I thought I'd bring it to attention anyway.

**Comment by KararTY** [comment]
This does indeed affect existing API keys but doesn't affect the code.

**However, an update to `providers.json` is necessary.** Here's the relevant commit for updating `providers.json`:
https://github.com/iamcal/oembed/commit/6f2af3104ca7fca8270916bb9a977257214ed3ad

When it comes to fixing existing API keys, one needs to do the new App Review process:
![image](https://user-images.githubusercontent.com/13697809/121345895-b4400700-c925-11eb-8c42-3aa2c539875e.png)
Also, they have an entire video over here https://developers.facebook.com/docs/app-review describing the process.

Also, services must now undergo yearly data checkup https://developers.facebook.com/docs/development/maintaining-data-access/data-use-checkup It's not very difficult, just lots of boxes to check.
