### ISSUE TITLE
Replace twitchemotes' API with Helix equivalents

### ISSUE THREAD

**Issue by zneix** [Chatterino/api#170]
In nicklaw5/helix 1.20.0 there were added methods supporting getting information about emote sets. It's worth checking if we can use that in order to replace third-party twirchemotes' API. Is it worth doing so though?

**Comment by zneix** [comment]
It's been discussed in chat that we would rather depend on official Twitch's API and query emotesets directly from Chatterino

For backwards compatibility we would still have to migrate, **because [Twitchemotes' API is being decomissioned](https://twitchemotes.com/apidocs)!!!**

**Comment by pajlada** [comment]
We might want to add emote support in api then too, as a way for old clients to get the same non-broken functionality
