### ISSUE TITLE
Make the Twitter link resolver resolve nitter links as well

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#229]
They're literally the same link format except for the domain name. (Probably a good first issue :wink: )

**Comment by Mm2PL** [comment]
There is a lot of nitter instances, we should only support the couple most used ones IMO.

**Comment by leon-richardt** [comment]
> There is a lot of nitter instances, we should only support the couple most used ones IMO.

Alternatively, we could consider trying to resolve anything that _looks_ like it might be following the Twitter link format (i.e., ignoring the domain name) as a Twitter link and fall back to the other resolvers if we get a bad response.

Just brainstorming, looking for additional opinions.

**Comment by pajlada** [comment]
Given our current architecture, I think supporting some specific domains is the way to go

**Comment by pajlada** [comment]
Given where Twitter is going, I don't feel comfortable spending more dev time on their platform.
