### ISSUE TITLE
Re-add youtube dislikes

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/api#257]
**What service do you want support added for?**

Return YouTube Dislikes

**Links**

https://returnyoutubedislikeapi.com/swagger/index.html

**Thumbnail**

YouTube dislikes next to the likes - where they were before (that were removed because youtube is a bunch of poopy doodoo heads)

**Additional information**

We'd look at using a 24h cache period, as they mention on their website, the "dislikes are cached and they aren't updated very frequently. It varies on video popularity but can take anywhere between a few hours and a few days days to update."

**Comment by pajlada** [comment]
This is not something we're look to add back unless officially supported by the YouTube API.
