### ISSUE TITLE
Explore if we can serve image thumbnail for WebP images with reasonable effort

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#259]
Example URL for which I would like a thumbnail served: https://artflowbucket-new.s3.amazonaws.com/generated/92fc3c00e617436e930cd9307974a72f.webp

This might need client-side support from Chatterino2 unless we want to convert the images before sending them

**Comment by KararTY** [comment]
Commenting on
> This might need client-side support from Chatterino2 unless we want to convert the images before sending them

WebP & animated WebP already works in Chatterino, you can see it in action here #312.
