### ISSUE TITLE
Add thumbnails for twitch sub emotes

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/api#26]
Hovering on a twitch emotes emote link would show a thumbnail of the sub emote, the emote name and the channel: https://twitchemotes.com/

**Comment by pajlada** [comment]
Could you give an example of a few twitch emote links?

**Comment by alazymeme** [comment]
For example: pajaW
Would fetch this link as the thumbnail: https://static-cdn.jtvnw.net/emoticons/v1/80481/3.0
Would fetch the channel name from here: https://api.twitchemotes.com/api/v4/emotes?id=80481
