### ISSUE TITLE
Add gif support in thumbnails

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/api#28]

**Comment by pajlada** [comment]
Please clarify what you mean (maybe give an example of something that should be a gif but isn't a gif)

**Comment by alazymeme** [comment]
> Please clarify what you mean (maybe give an example of something that should be a gif but isn't a gif)

Well at the moment, hovering over a gif just has it displaying a static image. Would be cool if it displayed the gif in it's entirety.

**Comment by gempir** [comment]
I tried adding this. It was super hard because the library we use for resizing doesn't support it and I couldn't find one that can in a way we can use.

**Comment by pajlada** [comment]
Fixed in #119
