### ISSUE TITLE
Tweet Link Thumbnails: Compose Multiple Images into Collage

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#347]
Tweets can have multiple images attached (see e.g. [this one](https://twitter.com/WitchcraftyYT/status/1557297274765692929)). It would be nice to compose all images into a collage for the generated thumbnail. In our current architecture, this would require some server-side processing. One tool that can do this is imagemagick via the [`montage` subcommand](https://www.imagemagick.org/script/montage.php) but there might be something else better suited for our purposes.

**Comment by KararTY** [comment]
(For reference)
Here's a related libvips issue on collage-making. https://github.com/libvips/libvips/issues/856
Available in govips as [ArrayJoin()](https://pkg.go.dev/github.com/davidbyttow/govips/v2/vips#ImageRef.ArrayJoin).
