### ISSUE TITLE
Youtube Shorts support

### ISSUE THREAD

**Issue by noiredayz** [Chatterino/api#355]
**What service do you want support added for?**

Preview/information for Youtube shorts, just like for "normal" Youtube videos, when posted using the "shorts" link format.

**Links**

https://www.youtube.com/shorts/Q9QdFTuuPOI
https://www.youtube.com/shorts/IefWjRpK4f0

**Thumbnail**

Same data as with "normal" youtube videos.

**Additional information**

When renaming the links to the standard watch?v= format the preview works normally.
![preview test](https://user-images.githubusercontent.com/85372821/187091234-d3604a1b-7eb5-4755-84b3-b0a216969f47.png)

Thank you!

**Comment by jammehcow** [comment]
Unlike #192, I believe this one should work with the current video resolver as IIRC shorts share the same ID space as videos. Would be keen to test this out

**Comment by jammehcow** [comment]
Looks like this was merged in #299 by Quinn, there just hasn't been a release of the API since then. This issue can be closed.

**Comment by noiredayz** [comment]
Cool, hope there will be a new release with that patch soon Prayge
Thank you for checking.
