### ISSUE TITLE
Add support for imgur.com subdomain imgur.io

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/api#361]
**What service do you want support added for?**

Apparently this is a subdomain of imgur.com - never heard of it until today but it seems valid. 
(honestly it looks like a future garbage layout they might implement on imgur.com)
I assume the current implementation will load the first image on this domain, similar to how the link resolver works with galleries.

![image](https://user-images.githubusercontent.com/41973452/190921976-3412112b-d463-4a53-b764-65de8d44df16.png)

**Links**
1.  https://imgur.io/5DaePph vs https://imgur.com/5DaePph
2.  https://imgur.io/xq9awUX vs https://imgur.com/xq9awUX

**Expected Thumbnail**

![image](https://user-images.githubusercontent.com/41973452/190921943-72535f5b-a375-490a-8856-5fa5785528e6.png)

**Additional information**

The imgur.io direct links use this ugly struct `https://i.imgur.com/xq9awUX_d.webp?maxwidth=640&shape=thumb&fidelity=medium` but since they are imgur.com links we already handle them.
![image](https://user-images.githubusercontent.com/41973452/190921864-71d1fc2d-6569-4ef6-b2bc-105a83f79054.png)

maybe we could use a list incase imgur adds any future domains ~~ 👻

**Comment by leon-richardt** [comment]
Since we have somewhat of a similar situation with Twitter and Nitter, it might be worth looking into a more general way to implement a multi-domain mechanism across multiple resolvers.

**Comment by leon-richardt** [comment]
This has been resolved by #365.

**Comment by pajlada** [comment]
Fixed in #365
