### ISSUE TITLE
Serve Link Info for PDFs

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#363]
## What service do you want support added for?

Similar to image files, serve thumbnails for PDFs. I'm not sure what a perfect behavior would be yet, this can be discussed in this issue.

A naive implementation might just take the first page of the thumbnail and render it to a PNG. More advanced implementations might attempt to parse text and provide that as the thumbnail text or arrange multiple PDF pages into a nice preview. 

## Links
1.  https://github.com/leon-richardt/green-networking/raw/194cfcc20bb059c62f5b305b1a58f17c28d8c1c4/Presentation/server_consolidation.pdf
2.  https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf

**Comment by leon-richardt** [comment]
The thumbnail could also include some metadata (e.g., as reported by tools like `pdfinfo`, for example). Interesting keys could be the title, number of pages, author, and date.

**Comment by KararTY** [comment]
Commenting on 
> A naive implementation might just take the first page of the thumbnail and render it to a PNG.
<details>
  <summary>(Click for image preview) libvips supports converting PDF to image formats.</summary>
  
  ![](https://trollface.tf/h1gJSCyR1Ifo.png)
</details>

It is possible to convert a selection of pages as well https://stackoverflow.com/a/71905045.
