### ISSUE TITLE
Ignore `?feature=share` at the end of youtube links

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/api#485]
I don't actually remember where these links are generated from (probably mobile or something), but I see them once and a while, and our resolver currently does not like them.

![image](https://github.com/Chatterino/api/assets/41973452/d06fd9e2-b083-413a-af00-a040bdb0f350)

**Comment by Mm2PL** [comment]
This is weird and non standard, it should be `/watch?v=...&feature=share`, not `?feature=share`.

**Comment by Felanbird** [comment]
Indeed, but the link work as expected and I'm very doubtful anyone watching this streamer is intentionally generating non-standard youtube links.
