### ISSUE TITLE
Some documentation and example config values are missing

### ISSUE THREAD

**Issue by zneix** [Chatterino/api#489]
With the addition of few new config options, including, but not limiting to `log-level`, `log-development`, etc. were never mentioned in CHANGELOG.md nor in config.yaml file. Possible values for these and possibly other options were never disclosed anywhere either.

I'm aware that missing changelog entries are something that can't really be undone now, but I'd love to have some clearer rule(s) for contributors or just say right here my thought as to when and what to include there - any change to config options, be it rename, addition or deletion should be carefully explained (or at least be mentioned and explained within `config.yaml` file / `--help` output).

**Comment by pajlada** [comment]
I believe those two PRs will resolve the missing documentation piece.

For future changes, I'll just make sure the changelog entry CI isn't overridden - the v2.0.0 release was a bit crazy

**Comment by zneix** [comment]
Oh I was not aware of issues with overriding documentation, that's understandable. These two PRs explain exactly what one would want to know, so I'm good with that, thank you for your help.
