### ISSUE TITLE
Twitter: Use OG resolver by default

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#499]
Since the Twitter API is now absurdly expensive, it is reasonable to assume that most hosters do not want to pay for an API key. Therefore, Twitter links should be handled by the Open Graph link resolver by default.

**Comment by M4tthewDE** [comment]
This seems to be quiet hard to implement, since twitter does not like automated access to their website. Without passing a valid value in the Cookies, the meta tags cannot be resolved.

**Comment by KararTY** [comment]
> This seems to be quiet hard to implement, since twitter does not like automated access to their website. Without passing a valid value in the Cookies, the meta tags cannot be resolved.

Valid point, the solution is to make sure the user-agent includes the word "bot":
See https://github.com/matrix-org/synapse/pull/11985#pullrequestreview-881653454

We will subsequently get all relevant OG tags.
